version: '3'
services:
  nd188-bert-ai:
    image: 'nd188-bert-ai:latest'
    ports:
      - "8888:8888"
    volumes:
      - './:/home/jovyan/work:rw'
    command:
      - /bin/bash
      - -c
      - |
        python -c "import torch; print(torch.__file__)" | grep "torch"
